config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  resources :users do
    member do
      get :confirm_email
    end
  end
  resources :sessions do
    member do
      get :logout
      get :slots
    end
  end
  resources :profiles
  resources :restaurants, except: [:destroy]
  delete '/restaurants/:id/delete' => 'restaurants#destroy', as: 'restaurants_delete'
  get '/restaurants/:id/delete' => 'restaurants#destroy'
  delete '/timeslots/:id/delete' => 'timeslots#destroy', as: 'timeslots_delete'
  get '/timeslots/:id/delete' => 'timeslots#destroy'
  resources :timeslots
  resources :reviews

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<head>
  <title>MealPals</title>
</head>

<body>
<div class = "title">
  <h1>Restaurants List</h1>
  <% if is_admin? %>
  <button type="button" class="btn btn-outline-primary"><%= link_to 'New Restaurant', new_restaurant_path %></button>
  <% end %>
</div>

<div class="container text-center">
  <div class = "row arrange">
    <% @restaurants.each do |restaurant| %>
      <div class="card" style="width: 18rem;">
          <img src="<%= restaurant.image.url %>" class="picture-src" id="wizardPicturePreview2" title="">
          <div class="card-body">
          <h5 class="card-title"><%= restaurant.name %></h5>
          <p class="card-text">Rating:<%= restaurant.rating %></p>
          <p class="card-text">Address:<%= restaurant.address %></p>
          <p class="card-text">Details:<%= restaurant.details %></p>
          <a><%= link_to 'Detail', restaurant, id: restaurant.name.parameterize.underscore+"_Detail" %></a>
          <% if is_admin? %>
            <a><%= link_to 'Edit', edit_restaurant_path(restaurant), id: restaurant.name.parameterize.underscore+"_Edit"%></a>
            <a><%= link_to 'Destroy', restaurants_delete_path(restaurant), method: :delete, data: { confirm: 'Do you want to delete the restaurant?' }, id: restaurant.name.parameterize.underscore+"_Destroy"%></a>
          <% end %>
          
        </div>
      </div>
    <% end %>
  </div>
</div>

</body>
