config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  resources :users do
    member do
      get :confirm_email
    end
  end
  resources :sessions do
    member do
      get :logout
      get :slots
    end
  end
  resources :profiles
  resources :restaurants, except: [:destroy]
  delete '/restaurants/:id/delete' => 'restaurants#destroy', as: 'restaurants_delete'
  get '/restaurants/:id/delete' => 'restaurants#destroy'
  delete '/timeslots/:id/delete' => 'timeslots#destroy', as: 'timeslots_delete'
  get '/timeslots/:id/delete' => 'timeslots#destroy'
  resources :timeslots
  resources :reviews

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base

    mount_uploader :image, ImageUploader
    
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def show
    restaurant_id = params[:id] # retrieve restaurant ID from URI route
    session[:restaurant_id] = restaurant_id
    @restaurant = Restaurant.find(restaurant_id) # look up restaurant by unique ID
    @reviews = Review.where(:restaurant_id => restaurant_id) 
    @timeslots = Timeslot.where(:restaurant_id => restaurant_id) 
    @current = Time.now.strftime("%Y-%m-%d %H:%M:%S")
    # will render app/views/restaurant/show.<extension> by default
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  # POST /restaurants
  def create
    puts restaurant_params
    if restaurant_params["name"] != '' && restaurant_params["rating"] != '' && restaurant_params["address"] != '' && restaurant_params["details"] != ''
      @restaurant = Restaurant.create!(restaurant_params)
      redirect_to root_url, notice: 'Restaurant was successfully created.'
    else
      flash[:error] = 'Failed to create the new restaurant. Please fill all the blank before submit.'
      redirect_to root_url
    end
  end

  # PATCH/PUT /restaurants/1
  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update_attributes!(restaurant_params)
      flash[:success] = "Restaurant was successfully updated."
      redirect_to root_url
    end
  end

  # DELETE 
  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to root_url, notice: 'Restaurant was successfully destroyed.'
  end

  private
    def restaurant_params
      params.require(:restaurant).permit(:name, :rating, :address, :details, :image)
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.text_field :rating %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :details %><br>
    <%= f.text_field :details %>
  </div>
  <div class="field">
    <%= f.label :image%><br>
    <%= f.file_field :image%>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary col-2'%>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show Detail', @restaurant %> |
<%= link_to 'Back', root_path %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/restaurants/show.html.erb
<h2>Details about <em><%= @restaurant.name %></em></h2>

<ul id="details">
  <li>
    Rating:
    <%  @restaurant.rating.to_i.times do  %>
      <i class="bi bi-star-fill" style="font-size: 2rem; color: cornflowerblue;"></i>
    <% end %>
  </li>
  <li>
    Address:
    <%= @restaurant.address %>
  </li>
</ul>

<details>
<summary>Description</summary>
<p id="description">
  <%= @restaurant.details %>
</p>
</details>

<details>
<summary>Reviews</summary>
<table class="table table-striped col-md-12" id="reviews">
  <thead>
    <tr>
      <th>Reviewer</th>
      <th>Rating</th>
      <th>Time</th>
      <th>Comment</th>
    </tr>
  </thead>
  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td>
          <%= User.find(review.user_id).username %>
        </td>
        <td>
          <%  review.rating.to_i.times do  %>
            <i class="bi bi-star-fill" style="font-size: 2rem; color: cornflowerblue;"></i>
          <% end %>
        </td>
        <td>
          <%= review.created_at %>
        </td>
        <td>
          <%= review.comment %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if current_user  %>
  <h3>New Review</h3>
  <%= form_tag reviews_path, :id => 'add_reviews', method: :post do %>
    <%= label :review, :rating, 'Rate the restaurant (5 to 1: Excellent to Bad):' %>
    <div class="rating">
      <input type="radio" value="5" name="review[rating]" id="review_rating_5" >
      <label class="text-white" for="review_rating_5">5</label>
      <input type="radio" value="4" name="review[rating]" id="review_rating_4" >
      <label class="text-white" for="review_rating_4">4</label>
      <input type="radio" value="3" name="review[rating]" id="review_rating_3" >
      <label class="text-white" for="review_rating_3">3</label>
      <input type="radio" value="2" name="review[rating]" id="review_rating_2" >
      <label class="text-white" for="review_rating_2">2</label>
      <input type="radio" value="1" name="review[rating]" id="review_rating_1" >
      <label class="text-white" for="review_rating_1">1</label>
    </div>
    
    <br>

    <%= label :review, :comment, 'Leave your comment', class: 'col-form-label' %>
    <%= text_field :review, :comment, class: 'form-control' %>
    <br/>
    <%= submit_tag 'Submit review', class: 'btn btn-primary' %>
  <% end %>
<% end %>
</details>



<details>
<summary>Hang Out Timeslots</summary>
<table class="table table-striped col-md-12" id="timeslot">
  <tbody>
    <% @timeslots.each do |timeslot| %>
      <tr>
        <td>
          <%= timeslot.user_id %>
        </td>
        <td>
          <%= timeslot.start_time %>
        </td>
        <% if timeslot.start_time < @current  %>
          <td>
          <%= 'Completed' %>
          </td>
        <% elsif timeslot.start_time == @current %>
          <td> 
          <%= 'In-progress' %>
          </td>
        <% else %>
          <td>
          <%= 'Upcoming' %>
          </td>
        <% end %>
        <% if session[:user_id] == timeslot.user_id %>
          <td>
            <%= link_to 'Delete', timeslots_delete_path(timeslot), method: :delete, data: { confirm: 'Are you sure?' }, id: timeslot.user_id.to_s+"_Delete" %>
          </td>
        <% else %>
          <% if Guest.where(:timeslot_id => timeslot.id).size == timeslot.max_number %>
            <td>
            <%= 'Full' %>
            </td>
          <% elsif Guest.where(:timeslot_id => timeslot.id , :user_id =>session[:user_id] ).size == 0 %>
            <% if session[:user_id]  %>
              <td>
              <%= link_to "Join", edit_timeslot_path(timeslot,:status=>"active"), id: timeslot.user_id.to_s+"_Join" %>
              </td>
            <% end %>
          <% end %>

          <% if Guest.where(:timeslot_id => timeslot.id , :user_id =>session[:user_id] ).size >= 1 %>
            <td>
              <%= link_to "Exit", edit_timeslot_path(timeslot,:status=>"inactive") , id: timeslot.user_id.to_s+"_Exit" %>
            </td>
          <% end %>
        <% end %>
        <td>
          <%= link_to 'Detail', timeslot, id: timeslot.user_id.to_s+"_Detail" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


<button type="button" class="btn btn-outline-primary"><%= link_to 'New timeslot', new_timeslot_path %></button>

</details>

<br></br>
<div id="end">
  <%= link_to 'Back to restaurant list', root_path, class: 'btn btn-primary col-2' %>
</div>