config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  resources :users do
    member do
      get :confirm_email
    end
  end
  resources :sessions do
    member do
      get :logout
      get :slots
    end
  end
  resources :profiles
  resources :restaurants, except: [:destroy]
  delete '/restaurants/:id/delete' => 'restaurants#destroy', as: 'restaurants_delete'
  get '/restaurants/:id/delete' => 'restaurants#destroy'
  delete '/timeslots/:id/delete' => 'timeslots#destroy', as: 'timeslots_delete'
  get '/timeslots/:id/delete' => 'timeslots#destroy'
  resources :timeslots
  resources :reviews

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MealPal</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.1/css/bootstrap-datepicker.min.css">

  <%= javascript_include_tag 'application' %>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.1/js/bootstrap-datepicker.min.js"></script>

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
  <link href="http://netdna.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.css" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-star-rating/4.0.2/css/star-rating.min.css" />
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-star-rating/4.0.2/js/star-rating.min.js"></script>


  <%= csrf_meta_tags %>
</head>
<body id="application">
<nav  id="application-nav" class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Meal Pals</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
<!--          <li><%#= link_to "#{current_user.username}", profiles_path %></li>-->
<!--          <li> <%#= link_to "Sign Out", logout_session_path(session[:user_id]) %></li>-->
          <li class="navbar-item avatar dropdown">
            <div class="picture-container dropdown-toggle "  id="avatarDropdown" data-toggle="dropdown"
                 aria-haspopup="true" aria-expanded="false">
              <div class="picture">
                <img src="<%= current_user.profile.avatar.url %>" class="picture-src" id="wizardPicturePreview" title="">
                <!--              <input type="file" id="wizard-picture" class="">-->
              </div>
            </div>
            <ul class="dropdown-menu" aria-labelledby="avatarDropdown">
              <li><%= link_to "My Profile", edit_profile_path(current_user.profile.id) %></li>
              <li><%= link_to "My Slots", slots_session_path(session[:user_id]) %></li>
              <li><%= link_to "Sign Out", logout_session_path(session[:user_id]) %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign In", new_session_path %></li>
        <% end -%>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container">
  <% if flash[:notice] %>
    <div class="alert alert-info alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <%= flash[:notice] %>
    </div>
  <% end %>
  <% if flash[:success] %>
    <div class="alert alert-success alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <%= flash[:success] %>
    </div>
  <% end %>
  <% if flash[:error] %>
    <div class="alert alert-danger alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <%= flash[:error] %>
    </div>
  <% end %>

  <%# if @user %>
  <%# if @user.errors.full_messages.any? %>
    <%# @user.errors.full_messages.each do |error_message| %>
<!--      <div class="alert alert-danger alert-dismissible" role="alert">-->
<!--        <button type="button" class="close" data-dismiss="alert" aria-label="Close">-->
<!--          <span aria-hidden="true">&times;</span>-->
<!--        </button>-->
        <%#= error_message if @user.errors.full_messages.first == error_message %>
<!--      </div>-->
    <%# end %>
  <%# end %>
  <%# end %>

  <%= yield %>

</div>

</body>
</html>